config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  root to: "users#index"
  resources :users do #, :only => [:index, :destroy]
  	resources :images, :only => [:index, :new, :create]
  end
  post "users/:id/images/new" => "images#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
#    attr_accessor :image_file_name

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

    has_many :images
    has_attached_file  :avatar, :styles => {medium: "300x300", thumb: "100x100"}
    validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, 
         :omniauth_providers => [:facebook, :vkontakte]

    def self.find_for_facebook_oauth access_token
    	if user = User.where(:email => access_token.extra.raw_info.email).first
    		user
    	else
    		User.create!(#provider: access_token.provider,
    			name: access_token.extra.raw_info.name,
    			email: 	  access_token.extra.raw_info.email,
    			password: Devise.friendly_token[0,20])
    	end
    end

    def self.find_for_vkontakte_oauth access_token
    	if user = User.where(:name => access_token.info.name).first
    		user
    	else
    		user = User.create!(#provider: access_token.provider,
    			name:  access_token.info.name,
    			email: access_token.info.name.split[0] + rand(265536).to_s + '@vk.com',
    			password: Devise.friendly_token[0,20])
    	end
    end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	current_user
  end

  def after_sign_out_path_for(resource_or_scope)
  	request.referrer
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	def index
#		@images = Image.where(user_id: params[:user_id])
	end

	def new
		@user = current_user
		@image = Image.new
	end

	def create
		@user = current_user
		@image = Image.new(image_params)
		@image.user_id = current_user.id
		if @image.save
			flash[:success] = "Изображение загружено!"
	      	redirect_to @user
	    else
	      	flash.now[:error] = "Ошибка загрузки!"
	      	redirect_to @user
	    end
	end	

	private
	def image_params
		params.require(:image).permit(:image, :description, :user_id)
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
  	@user = User.find_for_facebook_oauth request.env["omniauth.auth"]
  	if @user.persisted?
  		flash["notice"] = I18n.t "devise.omniauth_callbacks.sucsess", :kind => "Facebook"
  		sign_in_and_redirect @user, :event => :authentication
  	else
  		flash[:notice] = "Authentication error!"
  		redirect_to root_path
  	end
  end

  def vkontakte
  	@user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
  	if @user.persisted?
  		flash["notice"] = I18n.t "devise.omniauth_callbacks.sucsess", :kind => "Vkontakte"
  		sign_in_and_redirect @user, :event => :authentication
  	else
  		flash[:notice] = "Authentication error!"
  		redirect_to root_path
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.find_each do |user|
      return user.name
    end
  end

  def show
    @hash  = request.env["omniauth.auth"]
    @user = User.find(params[:id])
    @images = Image.where(user_id: @user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      redirect_to root_path
    end
  end

  def edit
    @user = current_user
  end

  def update
      @user = User.find(params[:id])
        if @user.update_attributes(user_params)
          flash[:success] = "Профиль обновлен!"
          redirect_to @user
        else
          flash[:error] = "Введите корректные данные!"
          render 'edit'
        end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :first_name, 
                :last_name, :birth_date, :self_info, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/new.html.erb
<center>
<%= form_for :image, html: { multipart: true } do |f| %>
	<%= f.label :description, "Description" %><br>
	<%= f.text_field :description, class: "text" %><br>
	<%= f.file_field :image %><br>
	<%= f.submit "Сохранить", class: "button" %>
<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Facebook" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        
        <h3>
          <% if user_signed_in? %>
            <%= link_to current_user.name, current_user %>
          <% else %>
            <%= link_to "Tiny facebook", root_path %> 
          <% end %>
          <%= image_tag @user.avatar, style: "display: block;float:right;", height: "70px" if @user.avatar %>
        </h3>
                      
        
                   
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>

              <li><%= link_to "Редактировать профиль", edit_user_path(current_user.id) %></li>
              <li><%= link_to "Выйти", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Войти с помощью:",  "#"  %></li>
            <li><%= link_to "Facebook",  user_facebook_omniauth_authorize_path  %></li>
            <li><%= link_to "Vkontakte", user_vkontakte_omniauth_authorize_path  %></li>
            <li><%= link_to "Зарегистрироваться", new_user_registration_path  %></li>

            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<center>
<%= form_for @user do |f| %>
	<%= f.label :name, "Name" %><br>
	<%= f.text_field :name, class: "text" %><br>
	<%= f.label :email, "E-mail" %><br>
	<%= f.text_field :email, class: "text" %><br>
	<%= f.label :first_name, "First name" %><br>
	<%= f.text_field :first_name, class: "text" %><br>
	<%= f.label :last_name, "Last name" %><br>
	<%= f.text_field :last_name, class: "text" %><br>
	<%= f.label :birth_date, "Birth date" %><br>
	<%= f.text_field :birth_date, class: "text" %><br>
	<%= f.label :self_info, "Self info" %><br>
	<%= f.text_area :self_info, class: "text" %><br>
	<%= f.file_field :avatar %><br>
	<%= f.submit "Сохранить", class: "button" %>
<% end %>
</center>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<br>

<%= form_for @user do |f| %>
	<%= f.label :name, "Name" %><br>
	<%= f.text_field :name %><br>
	<%= f.label :email, "E-mail" %><br>
	<%= f.text_field :email %><br>
	<%= f.label :first_name, "First name" %><br>
	<%= f.text_field :first_name %><br>
	<%= f.label :last_name, "Last name" %><br>
	<%= f.text_field :last_name %><br>
	<%= f.label :birth_date, "Birth date" %><br>
	<%= f.text_field :birth_date %><br>
	<%= f.label :self_info, "Self info" %><br>
	<%= f.text_area :self_info %><br>
	<%= f.submit "Создать" %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<h1><%= @user.name %>, id:<%= @user.id %></h1>
<h1><%= image_tag @user.avatar %></h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= link_to "Загрузить изображение", new_user_image_path(@user.id) %>

<ul>
	<% @images.each do |img| %>
		<li>
			<%= img.description %><br>
			<%= image_tag img.image %>
		</li><br><br>
	<% end %>
</ul>